filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/my.log
  include_lines: ['(\.*)(?:4[0-9]{12}(?:[0-9]{3})?|[25][1-7][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\d{3})\d{11})(\.*)',
                  '(\.*)([0-9]{9,18})(\.*)', '(\.*)([+]\d{2})?([\s])?\d{10}(\.*)']

processors:
  - add_id: ~
  - add_fields:
      target: project
      fields:
        application: '${APP_NAME}'
        host: '${HOST_NAME}'
  - script:
      lang: javascript
      tag: mask_sensitive
      source: >
        function process(event) {
          var msg = event.Get("message");
          msg = msg.replace(/(\.*)(?:4[0-9]{12}(?:[0-9]{3})?|[25][1-7][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\d{3})\d{11})(\.*)/g, "CC************");
          msg = msg.replace(/(\.*)([+]\d{2})?([\s])?\d{10}(\.*)/g, "MOB**********"); 
          msg = msg.replace(/(\.*)([0-9]{9,18})(\.*)/g, "BNK*********");
          event.Put("message", msg);
        }

#output.redis:
#  hosts: ["127.0.0.1"]
#  key: "prowler_alert_logs"
#  db: 0
#  timeout: 5

output.kafka:
  # initial brokers for reading cluster metadata
  hosts: ["127.0.0.1:9092"]
  topic: prowler_alert_logs
  partition.round_robin:
    reachable_only: false

  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

logging.to_files: true
logging.files:
  path: /usr/share/filebeat1.log

output.console:
  pretty:true

